namespace SIBR.Storage.Data.Models
{
    public enum UpdateType: byte
    {
        Player = 1,
        Team = 2,
        Stream = 3,
        Game = 4,
        Idols = 5,
        Tributes = 6,
        Temporal = 7,
        Tiebreakers = 8,
        Sim = 9,
        GlobalEvents = 10,
        OffseasonSetup = 11,
        Standings = 12,
        Season = 13,
        League = 15,
        Subleague = 16,
        Division = 17,
        GameStatsheet = 18,
        TeamStatsheet = 19,
        PlayerStatsheet = 20,
        SeasonStatsheet = 21,
        Bossfight = 22,
        OffseasonRecap = 23,
        BonusResult = 24,
        DecreeResult = 25,
        EventResult = 26,
        Playoffs = 27,
        PlayoffRound = 28,
        PlayoffMatchup = 29,
        Tournament = 30,
        Stadium = 31,
        RenovationProgress = 32,
        TeamElectionStats = 33,
        Item = 34,
        CommunityChestProgress = 35,
        GiftProgress = 36,
        ShopSetup = 37,
        SunSun = 38,
        LibraryStory = 39,
        Vault = 40,
        RisingStars = 41,
        FuelProgress = 42,
        Nullified = 43,
        Attributes = 44,
        Fanart = 45,
        GlossaryWords = 46,
        Library = 47,
        SponsorData = 48,
        StadiumPrefabs = 49,
        FeedSeasonList = 50,
        TheBeat = 51,
        TheBook = 52,
        ChampionCallout = 53,
        DaysSinceLastIncineration = 54,
        AvailableChampionBets = 55,
        PeanutPower = 56,
        GammaElections = 57,
        GammaElectionDetails = 58,
        GammaElection = 59,
        GammaSim = 60
    }
}